on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build_wheels:
    name: Build wheel for py${{ matrix.python-version }} ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      # list of github vm: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

        os:
          - name: "ubuntu-latest"

          - name: "macos-13"

          - name: "macos-14"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        id: py
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: Install Poetry
        run: |
          which python
          python --version
          which python3
          python3 --version
          echo "pythonpath: ${{ steps.py.outputs.python-path }}"
          ${{ steps.py.outputs.python-path }} --version
          pipx install poetry==1.8.3
          poetry env use ${{ steps.py.outputs.python-path }}
      
      - name: Build
        run: |
          poetry build
